version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
#    ports:
#      - '80:80'
#      - '81:81'
#      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      frontend:
        ipv4_address: 10.0.0.26
      backend:
        ipv4_address: 192.168.0.26
networks:
  frontend:
    name: qnet-static-eth0-ec3261
    external: true
  backend:
    name: proxymanager_bridge
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
    
