version: '3'

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log

services:
  emqx1:
    image: emqx:5.0.21
    environment:
    - "EMQX_NAME=emqx"
    - "EMQX_HOST=node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=manual"
    - "EMQX_NODE__COOKIE=yolo_mysecretcookie"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io, emqx@node2.emqx.io]"
    dns:
      - 10.0.0.22
      - 10.0.0.42
    volumes:
      #- vol-emqx-data:/opt/emqx/data
      - ./mnesia:/opt/emqx/data/mnesia
      #- vol-emqx-etc:/opt/emqx/etc
      #- vol-emqx-log:/opt/emqx/log
      - ./log:/opt/emqx/log
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    networks:
      macvlan20:
        ipv4_address: 10.0.2.25
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN


networks:
  macvlan20:
    name: macvlan20
    external: true
